### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.Resource

### ISSUE THREAD

**Issue by arya6000** [paulcwarren/spring-content-examples#3] opened 2019-05-07 19:15 UTC
When I add the following dependencies to my Spring boot project

```
		<dependency>
			<groupId>com.github.paulcwarren</groupId>
			<artifactId>spring-content-fs-boot-starter</artifactId>
			<version>0.8.0</version>
		</dependency>


		<dependency>
			<groupId>com.github.paulcwarren</groupId>
			<artifactId>spring-content-rest-boot-starter</artifactId>
			<version>0.8.0</version>
		</dependency>
```

and without adding or making any other changes. When I run the project I get the following exception

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
[32m :: Spring Boot :: [39m           [2m (v2.2.0.M1)[0;39m

[2m2019-05-07 15:11:15.281[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mrealestate.RealEstateApplication        [0;39m [2m:[0;39m Starting RealEstateApplication on 2OC-2OE with PID 15863 (/home/arya/Documents/workspace-spring-tool-suite/RealEstate/target/classes started by arya in /home/arya/Documents/workspace-spring-tool-suite/RealEstate)
[2m2019-05-07 15:11:15.283[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mrealestate.RealEstateApplication        [0;39m [2m:[0;39m No active profile set, falling back to default profiles: default
[2m2019-05-07 15:11:15.982[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mtrationDelegate$BeanPostProcessorChecker[0;39m [2m:[0;39m Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$d024049] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[2m2019-05-07 15:11:16.284[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.w.embedded.tomcat.TomcatWebServer [0;39m [2m:[0;39m Tomcat initialized with port(s): 8080 (http)
[2m2019-05-07 15:11:16.308[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Starting service [Tomcat]
[2m2019-05-07 15:11:16.309[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36morg.apache.catalina.core.StandardEngine [0;39m [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.16]
[2m2019-05-07 15:11:16.315[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.a.catalina.core.AprLifecycleListener  [0;39m [2m:[0;39m The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
[2m2019-05-07 15:11:16.377[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2019-05-07 15:11:16.377[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.web.context.ContextLoader           [0;39m [2m:[0;39m Root WebApplicationContext: initialization completed in 1071 ms
[2m2019-05-07 15:11:16.603[0;39m [33m WARN[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.w.s.r.ResourceHttpRequestHandler    [0;39m [2m:[0;39m Locations list is empty. No resources will be served unless a custom ResourceResolver is configured as an alternative to PathResourceResolver.
[2m2019-05-07 15:11:16.613[0;39m [33m WARN[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mConfigServletWebServerApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentPropertyCollectionRestController': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [internal.org.springframework.content.rest.controllers.ContentPropertyCollectionRestController] from ClassLoader [sun.misc.Launcher$AppClassLoader@764c12b6]
[2m2019-05-07 15:11:16.615[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.apache.catalina.core.StandardService  [0;39m [2m:[0;39m Stopping service [Tomcat]
[2m2019-05-07 15:11:16.626[0;39m [32m INFO[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mConditionEvaluationReportLoggingListener[0;39m [2m:[0;39m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[2m2019-05-07 15:11:16.633[0;39m [31mERROR[0;39m [35m15863[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentPropertyCollectionRestController': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [internal.org.springframework.content.rest.controllers.ContentPropertyCollectionRestController] from ClassLoader [sun.misc.Launcher$AppClassLoader@764c12b6]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:265) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1253) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1168) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:785) [spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:407) [spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1278) [spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1266) [spring-boot-2.2.0.M1.jar:2.2.0.M1]
	at realestate.RealEstateApplication.main(RealEstateApplication.java:11) [classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [internal.org.springframework.content.rest.controllers.ContentPropertyCollectionRestController] from ClassLoader [sun.misc.Launcher$AppClassLoader@764c12b6]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:583) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:568) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/hateoas/Resource
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_191]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_191]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_191]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:668) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.Resource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_191]
	... 25 common frames omitted
```

I have the following dependency also added

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-hateoas</artifactId>
		</dependency>
```

Any idea why this is happening?

**Comment by paulcwarren** [comment] 2019-05-07 20:43
My guess is that one or more of the hateoas classes cant be loaded because they have a dependency on something else that is in my examples project but not in yours yet.  But, let me investigate.  I'll get back soon.

**Comment by paulcwarren** [comment] 2019-05-08 04:33
Hey Arya,

I didnt have any luck reproducing your error I am afraid so I am not sure what is happening right now.  So, I checked in the example project that I was trying to reproduce through so we can both see the exact set of dependencies.  Note, I am using boot 2.1.4.RELEASE and the only dependency I have on the classpath is `spring-boot-starter-web`.  I did not need `spring-hateoas`.

My only thought is perhaps you are using a different version of Spring Boot?  Maybe the 1.x code line?   

I would be interested to know if this works for you as-is?

If you have a project that reproduces the problem then feel free to commit it to your github org and point me at it so I can pull it and try it for myelf.

**Comment by arya6000** [comment] 2019-05-08 04:43
I'm using 2.2.0.M1, I'm going to downgrade to see if that solves the issue

**Comment by arya6000** [comment] 2019-05-08 04:51
Downgrading to 2.1.4 solved the issue. 2.2.0.M1 will cause the exception

**Comment by paulcwarren** [comment] 2019-05-08 19:09
OK.  Great info.  Thanks Arya.  I'll investigate 2.2.0.M1 and let you know what I find, if anything.  Be in touch.

**Comment by paulcwarren** [comment] 2019-05-09 04:02
OK.  I figured out what is going on.  Spring Boot 2.2.0.M1 depends on Spring Data Moore that upgraded its spring-hateoas dependencies from 0.25.1 to 1.0.0.M1.  

In the 1.0.0.M1 of spring-hateoas they have significantly re-worked their API and as part of that renamed `Resource` to `EntityModel`.  There are details [here](https://spring.io/blog/2019/03/05/spring-hateoas-1-0-m1-released).   IMO this is a breaking change in a minor release but what can we do?  

To properly support this it is going to require a fork of the Spring Content code-line.  Either a top-level fork of the entire code base.  Perhaps Spring Content 1.x supports Spring Boot 2.2.0 and 0.x supports Spring Boot 2.1.x.  Or perhaps we just fork spring-content-rest (and it's boot-starter).  But then we would need a separate CI to release it independently to maven central.

I tried hacking around it by brute forcing some of the dependencies to 2.1.x dependencies and that may work in my simple project but I suspect in any real project its not going to.

A couple of questions; 
1. are you using Spring Data?  And does associating content with Spring Data entities make sense for you?  Or are you doing content-only operations?
2. what is your timeline on this?  do youu have any upcoming releases and/or deadlines?

**Comment by arya6000** [comment] 2019-05-11 01:36
I will be using it to upload images as you explained to me [here](https://stackoverflow.com/questions/55979442/creating-directory-and-uploading-images-to-remote-web-server/55979856#55979856)

My timeline is in a few months, there are no issues with using 2.1.4

**Comment by paulcwarren** [comment] 2019-05-13 14:47
Got it.  Sounds good.  I raised [this issue](https://github.com/paulcwarren/spring-content/issues/71) against the main spring-content repo to track upgrading to `2.2.0.RELEASE`

I'll close this one.  Please feel free to re-open if you disagree.

**Closed by paulcwarren** 2019-05-13 14:47 UTC
